### ISSUE TITLE
On Windows, exception ignored causes the break of program's execution

### ISSUE THREAD

**Issue by Marlysson** [ishepard/pydriller#21] opened 2018-11-25 00:09 UTC
When I run some operation provided by RepositoryMining at end of its execution occours the exception below:

```python
Exception ignored in: <finalize object at 0x3019fb0; dead>
```

My test:

```python
for commit in RepositoryMining("https://github.com/Marlysson/trackwork").traverse_commits():
    print(commit.hash, len(commit.modifications) )
```

I'm trying something wrong way or need a patch to fix them...

I wonder help if need some fix.

**Comment by ishepard** [comment] 2018-11-25 16:30
Hi @Marlysson ! Thank you for opening an issue. Can you give more details of your system? 
Python version and OS. 

I tried to run your code snippet but on my laptop (and on Travis) works. So I guess you are running on Windows? I don't have a Windows machine right now, but I am gonna try in the next days to reproduce it.

**Comment by Marlysson** [comment] 2018-11-25 18:54
Thanks for your reply.

**Python version:** Python 3.6.4
**OS Version:** Windows 10 ( 64 bits )

At final of exception shows this error:
```python
...
File "C:\Users\Marlysson\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 387, in _rmtree_unsafe
os.unlink(fullname)
PermissionError: [WinError 5] Acesso negado: 'C:\\Users\\MARLYS~1\\AppData\\Local\\Temp\\tmpyke6jsd0\\trackwork\\.git\\objects\\pack\\pack-cfcce62448b5fb055047519da127d1c143cc96b5.idx'
```

**Comment by Marlysson** [comment] 2018-11-28 14:17
Great . I will take a look it and see what can I do.

**Comment by ishepard** [comment] 2019-05-02 08:58
I will close the issue since it has not been updated in a long time. Feel free to re-open it when needed.

**Closed by ishepard** 2019-05-02 08:58 UTC
Labels: PR welcome, bug
