### ISSUE TITLE
Cannot traverse a specific commit

### ISSUE THREAD

**Issue by shehan** [ishepard/pydriller#149] opened 2020-12-05 15:36 UTC
I am mining a few repositories in GitHub using pydriller and encountered an issue where a specific commit I am trying to traverse does not exist in the cloned repository (default branch) but shows up on GitHub. 

This is the repository: https://github.com/dropwizard/metrics.git
These are a few commits that have the issue:
https://github.com/dropwizard/metrics/commit/64bc69ef4c547771f44f6b6b103cda7be2f0922b
https://github.com/dropwizard/metrics/commit/c40d697e8a86445f535ddc284354b297d9deaed0

This the code I'm using:
```
for commit in RepositoryMining(repo_path, single=commitsha).traverse_commits():
.
.
.
```
`traverse_commits()` throws an exception:

> ValueError: SHA b'c40d697e8a86445f535ddc284354b297d9deaed0' could not be resolved, git returned: b'c40d697e8a86445f535ddc284354b297d9deaed0 missing'

Let me know if there is a workaround to traverse these types of commits, or if I'm doing something wrong, or if this is out of scope for pydriller.

Thanks!

**Comment by simisimon** [comment] 2020-12-05 19:20
I think this problem is not caused in the pydriller but rather in the gitpython implementation, because I faced the same error. However, I used another framework that uses gitpython to check out commits from repositories and I think that pydriller also relies on git python to mine repositories.  I looked into the open issues of gitpython to see whether this problem is known, and I was right. There is currently an open issue: [Cannot retrieve commits from a specific repository](https://github.com/gitpython-developers/GitPython/issues/1016)

**Comment by ishepard** [comment] 2020-12-07 09:28
Hi @simisimon !
The commit you are looking at is not on the repo, it probably means that it belongs to a fork of the repository.
One easy way to check is to clone the repository, and then try to get the commit.
```
> git clone git@github.com:dropwizard/metrics.git
> git show 64bc69ef4c547771f44f6b6b103cda7be2f0922b
fatal: bad object 64bc69ef4c547771f44f6b6b103cda7be2f0922b
>
```
Hence, the problem is not of Pydriller nor of GitPython, it's just that the commit you are trying to analyze doesn't exist 😄

**Comment by simisimon** [comment] 2020-12-07 11:08
Ah, this makes sense. However, it seems to me that many repositories are affected by this problem when the commit history is analyzed with gitpython or pydriller. Have you experienced something similar? So, for my case, I'll implement a workaround to catch these cases. Thanks for your response.

**Comment by ishepard** [comment] 2020-12-07 12:25
TBH I never came across such a case. Generally, the users do something like:
```
git clone REPO

for commit in REPO:
    do something
```
Hence, only commits that are reachable from HEAD are actually traversed.

**Comment by shehan** [comment] 2020-12-08 02:27
Thanks for the detailed replies, @ishepard ! I had a feeling that this was not an issue with Pydriller, but just wanted to make sure that there was no workaround. As of now, I'm accessing details about these types of commits using the GitHub API. 

Is there any way I can use Pydriller's _Process Metrics_ and _Maintainability_ API to analyze these types of commits?

**Comment by ishepard** [comment] 2020-12-08 09:02
Hi Shenan! No there is no way to access those commits using Pydriller, as I use Git internally and Git is not able to do it, unfortunately. 

GitHub API/Pydriller is a combination that many users choose, though while Pydriller results are "polished", GitHub results are for you to polish. So all those commits that do not really exist need to be deleted, or skipped.

**Comment by ishepard** [comment] 2020-12-15 11:06
I'm closing this issue as it is not directly related to pydriller. Feel free to re-open it.

**Closed by ishepard** 2020-12-15 11:06 UTC

**Comment by mahtab-nejati** [comment] 2023-03-15 23:53
I have gotten the same error when trying the following code:

```
repo = Repository(REPOSITORY_PATH, 
                  only_modifications_with_file_types=patterns, 
                  only_in_branch='master', 
                  order='date-order')

for commit in repo.traverse_commits():
    print(commit.hash)
```

with `patterns` being a list of strings of file extensions.
However, by removing the `only_modifications_with_file_types` option, I don't get the same error. Does this help with handling this exception?
