### ISSUE TITLE
project_path and project_name in commit objects doesn't work

### ISSUE THREAD

**Issue by arghavanmo** [ishepard/pydriller#147] opened 2020-11-15 17:37 UTC
Hi,
There are two objects for the commit: **project_path** and **project_name**. When we call "project_path" receive an error that object does not exist. The second object "project_name" returns a 'list' however it supposed to return a 'string'.

for commit in RepositoryMining('path/to/the/repo').traverse_commits():
    print( commit.**project_path** )

**AttributeError**: 'Commit' object has no attribute 'project_path'

##########################################################
df = pd.DataFrame(columns=['proj_name'])

for commit in RepositoryMining('path/to/the/repo').traverse_commits():
    df = df.append({ 'proj_name': commit.**project_name** } , ignore_index=True)

**TypeError**: expected str, bytes or os.PathLike object, not list

**OS Version:**
 Windows 10

**Comment by ishepard** [comment] 2020-11-15 17:51
Hi @arghavanmo!

That's strange..Can you give me the entire code? 
If I try this in a repository:
```
for commit in RepositoryMining(".").traverse_commits():
    print(commit.project_name)
    print(commit.project_path)
    exit()
```
it works.

**Comment by arghavanmo** [comment] 2020-11-15 18:17
Sure, Here is the whole code:

tf_dt1 = datetime(2018,1, 1)
tf_dt2 = datetime(2020, 10, 30)

tf_source = pd.DataFrame(columns=['commit_ID', 'Author', 'Authored_Date','email','msg','Commiter','committer_date',
                                  'project_path','Commit_before', 'Commit_after','diff','Added_LOC','Removed_LOC',
                                 'Num_LOC','token_counts'])

path = ["https://github.com/NifTK/NiftyNet.git"]


for commit in pyd.RepositoryMining(path_to_repo=path, since=tf_dt1, to=tf_dt2).traverse_commits():
    for modified_file in commit.modifications:
        if modified_file.filename.endswith(".py"):
            tf_source = tf_source.append({'commit_ID': commit.hash, 'Author': commit.author.name, 
                                          'Authored_Date':commit.author_date , 'email': commit.author.email,
                                          'msg': commit.msg,'Commiter': commit.committer.name, 'committer_date': commit.committer_date,
                                          'project_path':project_path, 'Commit_before': modified_file.source_code_before,
                                          'Commit_after': modified_file.source_code,'diff':modified_file.diff,
                                          'Added_LOC':modified_file.added,'Removed_LOC':modified_file.removed,
                                          'Num_LOC':modified_file.nloc,'token_counts':modified_file.token_count}, ignore_index=True)

**Comment by ishepard** [comment] 2020-11-15 18:30
On my machine this works:
```
from pydriller import RepositoryMining
import pandas as pd

tf_source = pd.DataFrame(columns=['commit_ID', 'Author', 'Authored_Date','email','msg','Commiter','committer_date',
'project_path','Commit_before', 'Commit_after','diff','Added_LOC','Removed_LOC',
'Num_LOC','token_counts'])


for commit in RepositoryMining(path_to_repo="https://github.com/NifTK/NiftyNet.git").traverse_commits():
    for modified_file in commit.modifications:
        if modified_file.filename.endswith(".py"):
            tf_source = tf_source.append({'commit_ID': commit.hash, 'Author': commit.author.name,
                                          'Authored_Date': commit.author_date, 'email': commit.author.email,
                                          'msg': commit.msg, 'Commiter': commit.committer.name, 'committer_date': commit.committer_date,
                                          'project_path': commit.project_path, 'Commit_before': modified_file.source_code_before,
                                          'Commit_after': modified_file.source_code, 'diff': modified_file.diff,
                                          'Added_LOC': modified_file.added, 'Removed_LOC': modified_file.removed,
                                          'Num_LOC': modified_file.nloc, 'token_counts': modified_file.token_count}, ignore_index=True)
            print(tf_source)
            exit()
```
It prints:
```
                                  commit_ID    Author  ... Num_LOC token_counts
0  583e61a981064c90480bd0ef4736e94045879fef  Wenqi Li  ...    None         None
```

Can you try the following code on your machine please?
```
for commit in RepositoryMining(path_to_repo="https://github.com/NifTK/NiftyNet.git").traverse_commits():
    print(commit.project_name)
    print(commit.project_path)
    exit()
```

**Comment by ishepard** [comment] 2020-11-15 18:32
FYI, `project_path` is probably not useful to keep track of, as it's a path to a temporary directory that will be deleted when the program ends.

**Comment by arghavanmo** [comment] 2020-11-15 18:51
Thank you @ishepard. It's strange. I received the below error for 'project_path' when I run the code. However, it prints the 'project name'.  

```
import pydriller as pyd
import pandas as pd

for commit in pyd.RepositoryMining(path_to_repo="https://github.com/NifTK/NiftyNet.git").traverse_commits():
    print(commit.project_name)
    print(commit.project_path)
    exit()
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-6ffed094aa6d> in <module>
      1 for commit in pyd.RepositoryMining(path_to_repo="https://github.com/NifTK/NiftyNet.git").traverse_commits():
      2     print(commit.project_name)
----> 3     print(commit.project_path)
      4     exit()

AttributeError: 'Commit' object has no attribute 'project_path'
```

Also, when I run my code with 'project_name', I received the below error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-ee185f214a00> in <module>
      6                                           'Authored_Date':commit.author_date , 'email': commit.author.email,
      7                                           'msg': commit.msg,'Commiter': commit.committer.name, 'committer_date': commit.committer_date,
----> 8                                           'project_path':commit.project_name,'Commit_before': modified_file.source_code_before,
      9                                           'Commit_after': modified_file.source_code,'diff':modified_file.diff,
     10                                           'Added_LOC':modified_file.added,'Removed_LOC':modified_file.removed,

~\Anaconda3\lib\site-packages\pydriller\domain\commit.py in project_name(self)
    282         :return: project name
    283         """
--> 284         return Path(self._conf.get('path_to_repo')).name
    285 
    286     @property

~\Anaconda3\lib\pathlib.py in __new__(cls, *args, **kwargs)
   1008         if cls is Path:
   1009             cls = WindowsPath if os.name == 'nt' else PosixPath
-> 1010         self = cls._from_parts(args, init=False)
   1011         if not self._flavour.is_supported:
   1012             raise NotImplementedError("cannot instantiate %r on your system"

~\Anaconda3\lib\pathlib.py in _from_parts(cls, args, init)
    663         # right flavour.
    664         self = object.__new__(cls)
--> 665         drv, root, parts = self._parse_args(args)
    666         self._drv = drv
    667         self._root = root

~\Anaconda3\lib\pathlib.py in _parse_args(cls, args)
    647                 parts += a._parts
    648             else:
--> 649                 a = os.fspath(a)
    650                 if isinstance(a, str):
    651                     # Force-cast str subclasses to str (issue #21127)

TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by ishepard** [comment] 2020-11-16 09:22
Can you check which version of pydriller you are running? And also which version of Python.

**Comment by arghavanmo** [comment] 2020-11-17 21:15
Sure:
python: 3.7.4
pydrillr: 1.10.1

**Comment by ishepard** [comment] 2020-11-17 22:43
Can you update pydriller to the latest version? 1.15.3.
Let's see if it works

**Comment by arghavanmo** [comment] 2020-11-26 21:58
I updated. But still, I receive the error. I found that if I put the name of the repository as a "string" in **RepositoryMining**, it works fine:
`for commit in pyd.RepositoryMining(path_to_repo="https://github.com/NifTK/NiftyNet.git").traverse_commits():`

But when I path a list of repositories, then I receive the error:
`path = ["https://github.com/NifTK/NiftyNet.git"]
for commit in pyd.RepositoryMining(path_to_repo=path).traverse_commits():
    prj_name=commit.project_name
    print(prj_name)`

`ypeError                                 Traceback (most recent call last)
<ipython-input-37-960c8cae302c> in <module>
      1 for commit in pyd.RepositoryMining(path_to_repo=path).traverse_commits():
----> 2     prj_name=commit.project_name
      3     print(prj_name)

~\Anaconda3\lib\site-packages\pydriller\domain\commit.py in project_name(self)
    282         count_additions = 0
    283 
--> 284         for line in lines:
    285             line = line.rstrip()
    286             count_deletions += 1

~\Anaconda3\lib\pathlib.py in __new__(cls, *args, **kwargs)
   1008         if cls is Path:
   1009             cls = WindowsPath if os.name == 'nt' else PosixPath
-> 1010         self = cls._from_parts(args, init=False)
   1011         if not self._flavour.is_supported:
   1012             raise NotImplementedError("cannot instantiate %r on your system"

~\Anaconda3\lib\pathlib.py in _from_parts(cls, args, init)
    663         # right flavour.
    664         self = object.__new__(cls)
--> 665         drv, root, parts = self._parse_args(args)
    666         self._drv = drv
    667         self._root = root

~\Anaconda3\lib\pathlib.py in _parse_args(cls, args)
    647                 parts += a._parts
    648             else:
--> 649                 a = os.fspath(a)
    650                 if isinstance(a, str):
    651                     # Force-cast str subclasses to str (issue #21127)

TypeError: expected str, bytes or os.PathLike object, not list`

**Comment by ishepard** [comment] 2020-11-27 09:28
Unfortunately I can not reproduce the error on my laptop. If I run this code:
```
path = ["https://github.com/NifTK/NiftyNet.git"]
for commit in RepositoryMining(path_to_repo=path).traverse_commits():
    print(commit.project_name, commit.project_path)
```
it works.

Can you try to debug the error on your laptop and maybe fix it? You can open a PR if you find where the error is 😃

**Comment by ishepard** [comment] 2020-12-15 11:07
I am closing this issue, feel free to re-open it if the problem persists!

**Closed by ishepard** 2020-12-15 11:07 UTC

**Comment by JulianVolodia** [comment] 2021-06-09 13:23
Hi @ishepard I think I know what was the reason.

> ```
>     @property
>     def project_path(self) -> str:
>         """
>         Return the absolute path of the project.
> 
>         :return: project path
>         """
>         return str(Path(self._conf.get("path_to_repo")))
> ```

venv/lib/python3.9/site-packages/pydriller/domain/commit.py

> TypeError: expected str, bytes or os.PathLike object, not list

was raised for @arghavanmo but then the \@property not exists if while evaluation of that property raises the error.

https://stackoverflow.com/a/37317736

> --> 649                 a = os.fspath(a)
>     650                 if isinstance(a, str):
>     651                     # Force-cast str subclasses to str (issue #21127)
> 
> TypeError: expected str, bytes or os.PathLike object, not list
> 

so it was a list but the Path was not accepting that. Code works until accessing the property (w/o checking if it exists).

so if Path is iterable it shall be checked and return the List[str] ?

**Comment by JulianVolodia** [comment] 2021-06-09 13:27
I seen similar outcome but I believe from another reasons:
got AttributeError with 'Commit' object has no attribute 'modifications'

mycode1
```
for commit in repository_mining.traverse_commits():
  was_commit_created, author_created = self.create_commit_object(commit)
```
mycode2
```
def create_commit_object(self, commit):
  for modification in commit.modifications:
    modified_files = modified_files + modification.filename + self.separator
```

```
for modification in commit.modifications: …
Variable	Value
added_lines	
0
commit	
<pydriller.domain.commit.Commit object at 0x7fa5d95b5ee0>
modified_files	
''
no_of_modified_files	
0
removed_lines	
0
```

so... it was https://github.com/ishepard/pydriller/commit/db9621c622ed0997ee914034329870c030420e48 commit change and one can't distinguish easily. Like, with one raised exception shoot in head but with checking repo and code analysis so I think we should try-except this cases?

What You think @ishepard ? How could I help ? :)
