### ISSUE TITLE
Commit.modifications returns non-existing modifications

### ISSUE THREAD

**Issue by vovak** [ishepard/pydriller#38] opened 2019-04-16 00:36 UTC
Steps to reproduce:

1. Create a sample repository using this Bash script:
```
#!/bin/bash

mkdir repr
cd repr
git init .

echo "file A, version 1" > A
git add A
git commit -m "initial commit"

git branch new_branch
git checkout new_branch
echo "file B, version 1" > B
git add B
git commit -m "second version of file B"

git checkout master
echo "file A, version 2" > A
git add A
git commit -m "second version of file A"

git merge --no-edit new_branch
```

2. Run a Python script below that prints all file modifications.
The code below assumes pydriller 1.7, installed via pip
```
from pydriller import RepositoryMining

PATH_TO_REPOSITORY = "repr"

for i, commit in enumerate(RepositoryMining(PATH_TO_REPOSITORY).traverse_commits(), start=1):
    mods = commit.modifications

    if (len(mods) == 0): print(f"{commit.hash}: no files changed")

    for m in mods:
        print(f"{commit.hash}: {m.change_type.name} {m.new_path}")
```

Expected output:
```
a6763da25856674843cff0105c162e3e4ead57b7: ADD A
720f2c15cb164a51b057975640f1184780e714b3: ADD B
6bebe30fbb1395775279cafc7f2dd8df365cbea2: MODIFY A
6df08c17e08eae9623f445994544a43bc5ba913d: no files changed
```

Actual output:
```
a6763da25856674843cff0105c162e3e4ead57b7: ADD A
720f2c15cb164a51b057975640f1184780e714b3: ADD B
6bebe30fbb1395775279cafc7f2dd8df365cbea2: MODIFY A
6df08c17e08eae9623f445994544a43bc5ba913d: ADD B
```

File B appears to have been created again in the last commit.

Running `git show 6df08c1 --pretty=raw` to list the changes in the last commit yields the following:
```
Vladimirs-MacBook-Pro:repr vovak$ git show 6df08c1 --pretty=raw
commit 6df08c17e08eae9623f445994544a43bc5ba913d
tree cc7d1f6be10849812cf58d519538dbd36d82e261
parent 6bebe30fbb1395775279cafc7f2dd8df365cbea2
parent 720f2c15cb164a51b057975640f1184780e714b3
author Vladimir Kovalenko <v.v.kovalenko@tudelft.nl> 1555373952 +0200
committer Vladimir Kovalenko <v.v.kovalenko@tudelft.nl> 1555373952 +0200

    Merge branch 'new_branch'

```

`git show` demonstrates that no files were changed in this last commit, but pydriller presents it as if a file was created there.

**Comment by ishepard** [comment] 2019-04-16 08:47
thank you @vovak for the PR! So I investigated the problem, and I think I found where the problem is.

To retrieve the modified files in every commit, I do `git diff parent_commit current_commit`. In cases in which there is more than 1 parent (i.e,, merges), I choose the left parent (parent[0]). 
This, however, seems to be different from the default behaviour of Git (all the merges commits that I analysed so far have 0 modified files). I will investigate how Git handles this situation and come back to you soon.

**Comment by vovak** [comment] 2019-04-16 10:02
Indeed, by ignoring other parents you are guaranteed to get such ghost events quite often. In this case, the tree of the left parent doesn’t have the B, so it appears as a new file in the diff (again, after a genuine add event in a branch, thus incorrectly). It is already present in the tree of the right parent, however, and should not be counted as added in the merge commit, as it was already added before.
Thus, you need to consider all parents to avoid duplicate events in modifications.

Verstuurd vanaf mijn iPhone

**Comment by vovak** [comment] 2019-04-16 10:05
cc @mark-selyaeff @jzuken

**Comment by ishepard** [comment] 2019-04-16 10:16
Yes indeed, the behaviour is definitely wrong. The problem seems to rely on how `git diff` works. See this [answer](https://stackoverflow.com/a/40986893/7053584). Using `git diff` on the merge commits prints the wrong result (even with the `-c` option), while instead using `git diff-tree` works perfectly, because it uses the combined diff (and this is why `git show` also works, because according to the documentation it uses `git diff-tree`). 

So the solution is to use the combined diff, instead of the normal diff. Now the problem is how to force GitPython to do it. PR are welcome as well 😄

**Comment by mauricioaniche** [comment] 2019-04-16 11:12
I have this issue in all my studies, too... Tricky to solve. But maybe if Pydriller solves it, I'll never have this problem again.

What would be the best approach here? Maybe get the diff between <commit, left> and <commit, right>, and then, decide which one to believe? Like, if one says _add_, but the other says _modified_, then we go for the _modified_ one?

**Comment by ishepard** [comment] 2019-04-16 11:30
So, after reading the docs and some forum, I think the best approach is to retrieve the combined diff, instead of the normal diff (this of course if GitPython allows me to do it, otherwise I will have to do a PR on GitPython). 

According to the docs, the combined diff is the diff that represents only the files that were in more than 1 branch (the so called "conflicts"). 
So, if branch1 has file A, branch2 has file B, and we merge them, the combined diff is empty (right now instead is B). 
If branch1 has file A and B, branch 2 has file B and C, the merge is file B (this will be the conflict indeed).

The trivial approach would be to ask the diff for all the branches, and keep only the files in common. This however is quite expensive. 
The non trivial approach would be to use `git diff-tree` instead of `git diff`, that it outputs the combined diff by default. However, this is not the normal behaviour of GitPython so I need to check if it's possible. There is a [PR about this](https://github.com/gitpython-developers/GitPython/pull/740/files) actually.

**Comment by ishepard** [comment] 2019-04-16 13:06
@vovak I created a branch and committed a solution (taken from the [PR](https://github.com/gitpython-developers/GitPython/pull/740/files) on GitPython), and submitted a test as well. Now it doesn't print all the modified file, and should print only the combined diff. I am gonna further check how it behaves on larger projects.

**Comment by ishepard** [comment] 2019-04-19 09:28
ehi @vovak, I created a PR #39 that should solve the problem. If you have time to check whether it works on some cases would be awesome (I checked on your example and it works indeed).

**Closed** 2019-05-02 08:56 UTC
