### ISSUE TITLE
Use pygit2 where possible

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#54] opened 2019-08-06 07:30 UTC
`gitpython`'s performance is not great, as it uses subprocess to spawn a git process for every command.
Using `pygit2` can greatly improve performance, even though it's a bit harder to use.

**Comment by ishepard** [comment] 2019-08-06 08:03
Hi @marco-c, yes I already saw that library and indeed it looks a bit more complicated than GitPython (even though the commands that we use, like `git log` and `git show` are almost identical). Right now, using GitPtyhon, we can achieve an average of 55 commits per second, which is for the general user a good compromise between simplicity and speed.

However, I will make a note to checkout this library and see whether we can achieve better performance and still keep things simple. 
Right now, as you know, I am quite busy with ICSE, but let's talk again after the deadline :)

**Comment by ishepard** [comment] 2019-08-18 09:52
I was playing around a bit on this: I've written a piece of code to iterate over all the commits, get the diffs, and get the source code of every file in the commit. This is the code:
```
dt1 = datetime.now()
for commit in repo.walk(repo.head.target):
    if len(commit.parents) == 1:
        diff = repo.diff(str(commit.parents[0].id), str(commit.id))
        for p in diff:
            if str(p.delta.status_char()) == 'D':
                blob = commit.parents[0].tree[p.delta.old_file.path].id
                d = repo[blob].data.decode('utf-8', 'ignore')
            else:
                blob = commit.tree[p.delta.new_file.path].id
                d = repo[blob].data.decode('utf-8', 'ignore')
dt2 = datetime.now()
print(f'pygit2: it took {dt2 - dt1}')

dt1 = datetime.now()
repo = Repo('/Users/dspadini/Documents/pydriller/')
for commit in repo.iter_commits('master'):
    if len(commit.parents) == 1:
        diff_index = commit.parents[0].diff(commit, create_patch=True)
        for diff in diff_index:
            try:
                if diff.deleted_file:
                    sc_before = diff.a_blob.data_stream.read().decode('utf-8', 'ignore')
                else:
                    sc_before = diff.b_blob.data_stream.read().decode('utf-8', 'ignore')
            except (UnicodeDecodeError, AttributeError, ValueError):
                pass
dt2 = datetime.now()
print(f'gitython: it took {dt2 - dt1}')
```
The result is astonishing:
```
pygit2: it took 0:00:00.657458
gitython: it took 0:00:03.315849
```
I think it's a good moment for me to start working on Pydriller 2.0 :) 
The only thing is that it took me 1 hour to install pygit2, due to its dependency with libgit2. I'll work on that.

**Comment by ishepard** [comment] 2019-08-27 14:29
Ok, in the branch `pygit2` I almost finished the porting to pygit2. All the tests pass. 
I was looking at `test_memory_consumption` and, to analyze 1 year of hadoop` we have:
```
GitPython: 64seconds
pygit2: 40seconds
```
This means that with pygit2 we are ~40% faster.

**Comment by ishepard** [comment] 2019-09-18 07:33
As explained in the PR, pygit2 has problems with resources and the improvement doesn't seem to justify this. So I am gonna close this issue for now

**Closed by ishepard** 2019-09-18 07:33 UTC
Labels: enhancement

**Comment by marco-c** [comment] 2019-09-18 08:10
Oh, that's a pity :(
The memory issue is probably due to some leak in pydriller, as pygit2 is just bindings to libgit2 (the `git` binary uses `libgit2`, and `gitpython` uses the `git` binary, so if the memory issue was due to `libgit2` it would affect `gitpython` too).

**Comment by ishepard** [comment] 2019-09-18 08:23
Indeed I thought so too, but it's not the case.
I compared GitPython and Pygit2 directly. Here's the code:

```
start = datetime(2017, 1, 1, tzinfo=timezone.utc)
end = datetime(2017, 7, 1, tzinfo=timezone.utc)

### PYGIT2
proc = psutil.Process(os.getpid())
for commit in repo.walk(repo.head.target):
    t = datetime.utcfromtimestamp(commit.commit_time)
    if t < start or t > end:
        continue
    if len(commit.parents) == 1:
        diff = repo.diff(str(commit.parents[0].id), str(commit.id))
        for p in diff:
            # get source code of file
            print(proc.memory_info()[0] / (2 ** 20))

### GitPython
p = psutil.Process(os.getpid())
for commit in gitpythonrepo.iter_commits():
    if commit.committed_datetime < start or commit.committed_datetime > \
            end:
        continue
    diff_index = commit.parents[0].diff(commit, create_patch=True)
    for diff in diff_index:
        # get source code of file
        print(p.memory_info()[0] / (2 ** 20))
```

And the results for Pygit2 is https://pastebin.com/s4Q8nziK
For Gitpython is https://pastebin.com/DX1W38sC.

The difference is crazy high. And notice that in pygit2 the memory continues to go up, while for Gitpython it stays still to 25MB. 
Strangely enough, for pygit2 **it starts** at 75MB, and then goes up every commit.

**Comment by ishepard** [comment] 2019-09-18 08:25
I don't think the problem is libgit2, I think the problem is pygit2. They probably don't use Generators and use a lot of dictionaries. Dictionaries in python requires quite a lot of memory

**Comment by marco-c** [comment] 2019-09-18 08:38
> I don't think the problem is libgit2, I think the problem is pygit2. They probably don't use Generators and use a lot of dictionaries. Dictionaries in python requires quite a lot of memory

A large part of pygit2 is just C code, so I would be surprised if that was the case. For example, here's the implementation of walk: https://github.com/libgit2/pygit2/blob/24d176c3d9b72d33d604e3c2cf08557285acb0af/src/repository.c#L631. The situation you're describing seems more like a memory leak rather than simply using more memory because of lists/dictionaries.

I'll file an issue on their repo with your test case and see what they say.

**Comment by ishepard** [comment] 2019-09-18 08:40
That's true. Let's see what they have to say.
